import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: { height: '100vh', display: 'flex', background: '#050505', color: '#fff', fontFamily: 'Inter, sans-serif' },
  loading: { height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#000' },
  controlPanel: { flex: 1, padding: 30, display: 'flex', flexDirection: 'column', gap: 20, overflowY: 'auto' },
  audiencePanel: { width: 350, padding: 30, background: '#0a0a0a', borderLeft: '1px solid #222' },
  header: { display: 'flex', justifyContent: 'space-between' },
  title: { fontSize: '0.8rem', letterSpacing: 2, opacity: 0.6 },
  statusPill: { fontSize: '0.7rem', fontWeight: 900, background: '#111', padding: '4px 12px', borderRadius: 10 },
  masterActions: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 },
  mainBtn: { border: 'none', borderRadius: 8, padding: 20, color: '#fff', fontWeight: 900, cursor: 'pointer', textAlign: 'left' },
  subBtn: { display: 'block', fontSize: '0.6rem', opacity: 0.8, fontWeight: 400, marginTop: 4 },
  settingsGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 },
  settingsSection: { background: '#111', padding: 15, borderRadius: 8, border: '1px solid #222', marginBottom: 10 },
  slider: { width: '100%', accentColor: '#f1c40f' },
  numInput: { background: '#000', border: '1px solid #333', color: '#f1c40f', width: 50, padding: 5, borderRadius: 4, fontWeight: 900 },
  toggleBtn: { border: 'none', color: '#fff', padding: '5px 10px', borderRadius: 4, fontSize: '0.7rem', cursor: 'pointer' },
  select: { flex: 1, background: '#000', color: '#fff', border: '1px solid #333', padding: 10, borderRadius: 5, cursor: 'pointer' },
  refreshBtn: { background: '#333', color: '#fff', border: 'none', padding: '0 15px', borderRadius: 5, cursor: 'pointer', fontSize: '0.7rem' },
  liveIntelPanel: { background: '#111', padding: 20, borderRadius: 12, border: '1px solid #f1c40f', display: 'flex', gap: 20 },
  answerListHost: { marginTop: 10, display: 'flex', flexDirection: 'column', gap: 5 },
  answerRowHost: { display: 'flex', fontSize: '0.85rem' },
  queueScroll: { maxHeight: '150px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 5 },
  queueItem: { display: 'flex', alignItems: 'center', background: '#000', padding: 8, borderRadius: 6, border: '1px solid #222' },
  removeBtn: { background: 'none', border: 'none', color: '#ff3b30', fontSize: '1rem', cursor: 'pointer', padding: '0 10px' },
  filterSection: { background: '#111', padding: 15, borderRadius: 8, border: '1px solid #222' },
  autoPopulateBtn: { width: '100%', marginTop: 15, background: '#f1c40f', color: '#000', border: 'none', borderRadius: 4, padding: '8px', fontSize: '0.7rem', fontWeight: 900, cursor: 'pointer' },
  tagCloud: { display: 'flex', flexWrap: 'wrap', gap: 5 },
  tag: { border: 'none', borderRadius: 4, padding: '4px 8px', fontSize: '0.7rem', cursor: 'pointer', fontWeight: 700 },
  label: { fontSize: '0.6rem', fontWeight: 900, opacity: 0.5, letterSpacing: 1, marginBottom: 5, display: 'block' },
  input: { flex: 1, background: '#111', border: '1px solid #222', padding: 12, borderRadius: 8, color: '#fff' },
  searchBtn: { padding: '12px 20px', borderRadius: 8, background: '#fff', border: 'none', fontWeight: 900, cursor: 'pointer' },
  resultsList: { maxHeight: 150, overflowY: 'auto', marginTop: 10 },
  resultItem: { padding: 10, fontSize: '0.8rem', borderBottom: '1px solid #111', cursor: 'pointer', display: 'flex', justifyContent: 'space-between' },
  teamList: { display: 'flex', flexDirection: 'column', gap: 10 },
  teamRow: { display: 'flex', alignItems: 'center', gap: 10, padding: 12, background: '#111', borderRadius: 8 },
  colorBar: { width: 3, height: 25 },
  teamScore: { fontWeight: 900, fontSize: '1.2rem' },
  dangerZone: { borderTop: '1px solid #330000', paddingTop: 20, marginTop: 10 },
  resetBtn: { width: '100%', background: 'transparent', border: '1px solid #ff0000', color: '#ff0000', padding: 15, borderRadius: 8, fontWeight: 900, cursor: 'pointer', fontSize: '0.7rem' }
};